#!/usr/bin/python

import cgi
form = cgi.FieldStorage()
path = form.getvalue("path")
with open("likes.txt", "a") as fl:
    fl.write(path)
    fl.write("\n")
print("Content-type: text/html", end="\r\n\r\n")
print("Location: /server/reply-like.html", end="\n\n")
