#+OPTIONS: html-style:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./style.css"/>
#+HTML_HEAD_EXTRA: <script type="text/javascript" src="./script.js"></script>
#+HTML_HEAD_EXTRA: <link rel="icon" type="image/png" href="../favicon.png">
#+HTML_HEAD_EXTRA: <style> h2 { font-size: 15pt; } </style>
#+HTML_LINK_UP: ../home/index.html
#+HTML_LINK_HOME: ../home/index.html
#+PROPERTY: RSS_URL_BASE https://archive.casouri.co.uk/note/
#+MACRO: post (eval (format "* [[./$2index.html][$1]]\n  :PROPERTIES:\n  :RSS_RELATIVE_LINK: $2\n  :RSS_URL_BASE: https://archive.casouri.co.uk/note/\n  :PUBDATE: %s\n  :END:" (with-current-buffer (find-file "$2index.org") (plist-get (car (cdr (car (plist-get (org-export-get-environment) :date)))) :raw-value))))

#+TITLE: Notes

{{{post(Blog in Org Mode\, Revisited,2018/blog-in-org-mode-revisited/)}}}
How to build a blog with Org Mode and without any framework.

{{{post(Easy Bindings when Region Is Active,2018/easy-bindings-when-region-is-active/)}}}
Bind a set of easy bindings when region is active.

{{{post(Emacs Keymap Precedence,2018/emacs-keymap-precedence/)}}}
Which keymap overrides which in Emacs.

{{{post(Ivy to Helm,2018/ivy-to-helm/)}}}
How and why I switched from ivy to Helm.

{{{post(My Favorite Musicians,2018/my-favorite-musicians/)}}}
A list of my favorite musicians.

{{{post(Who Called My Function?,2018/who-called-my-function/)}}}
Check who called the innocent function in Emacs. Useful to find the culprit in start up process.

{{{post(Emacs Gateway Drug,2018/emacs-gateway-drug/)}}}
Tricks that can lure your friend into using Emacs.

{{{post(Org Mode in Source File,2018/org-mode-in-source-file/)}}}
Create header and fold/unfold entries in any source file.

{{{post(Retro Terminal Blog Style,2018/retro-terminal-blog-style/)}}}
I made my home page looks like a secret SCP style retro terminal archive.

{{{post(Join Chat on IRC,2018/join-chat-on-irc/)}}}
How use this cool protocol to chat with hackers.

{{{post(Wanderlust,2018/wanderlust/)}}}
Some notes I took when trying to setup Wanderlust.

{{{post(My Favorite Animes,2018/my-favorite-animes/)}}}
A list of animes that I love.

{{{post(Use Indirect Buffers,2018/use-indirect-buffers/)}}}
A cool hidden feature of Emacs.

{{{post(Basic Sorting Algorithm,2018/basic-sorting-algorithm/)}}}
Study note about basic sorting algorithms.

{{{post(Cool URI Does not Change,2018/cool-uri-does-not-change/)}}}
An article I read and agree with.

{{{post(Blog with only Org Mode,2018/blog-with-only-org-mode/)}}}
How to build blog site with only Org Mode (and HTML, CSS and JavaScript).

{{{post(Note About Domain and DNS,2018/note-about-domain-and-dns/)}}}
Some notes I take when trying to add a custom domain to GitHub Pages.

{{{post(Fancy startup screen for emacs,2018/fancy-startup-screen-for-emacs/)}}}
Display something fancier on startup.
