#+SETUPFILE: ../../setup.org
#+TITLE: Ivy to Helm
#+DATE: <2018-11-15 Thu>
#+TAGS: Emacs
#+HIDE: true

When I started using Emacs (2017), people are switching from Helm to ivy[fn:1].
Ivy is considered minimal, elegant and transparent; and people like those.
Helm, on the other hand, is considered heavy, overblown and kinda sorta a blackbox.
Naturally I switched to ivy (I was using Spacemacs, and the default is Helm) for
all the positive comments about it.
Also because configuring Helm was not easy nor straightforward for me at the time.

After using ivy for a while, I see a problem about it: it uses the minibuffer.
Because ivy uses the minibuffer, it can't complete when you /are/ in the minibuffer.
E.g., if you are using ivy to complete something and want to paste from kill-ring,
which tries to use ivy for completion, it doesn't work. Emacs warns you that you are
opening minibuffer while in minibuffer, and refuses to do that.

That's the only reason, really, because ivy and Helm are both pretty feature-complete,
you don't lost anything switching.
Thanks to my modular configuration, switching isn't a lot of work, either.
Plus, now that I have more experience with Emacs, configuring Helm (mostly copying from [[https://github.com/hlissner/doom-emacs][doom-emacs]])
isn't hard as it used to be.

Some differences between ivy and helm:

1. Helm is visually more elaborate, and has more features. Some argue that Helm has too many (unessessary)
   features, but I do like more tools.
1. ivy's completing paradigm is more "traditional" Emacs, while Helm feels (and is) quite foreign.
   See [[https://github.com/emacs-helm/helm/wiki#helm-completion-vs-emacs-completion][official comparison]]. On example: with ivy (and ido and vanilla Emacs),
   you look at what you type in the minibuffer;
   with Helm, you look at the completing display.
1. Helm is slower than ivy. However, it is still fast. And ivy is super fast.
1. When completing paths, =/= completes in ivy, =RET= completes in Helm; =DEL= deletes to the last
   backslash in ivy, and =DEL= in Helm behaves the same and deletes one character.
1. Helm uses window or a frame to display completing window, while ivy uses the minibuffer.
   Because Helm uses the window, you can configure it to only split the current window.
   Ivy, on the other hand, always displays on the bottom of the frame.

There is one annoyance about Helm: by default the helm completion window took half the screen,
and that's too big. Decreasing it, though, however, isn't straightforward.

=helm-display-buffer-height= is not what you want.
It specifies the height if you configure Helm to open in another frame, rather than a window.
Instead, turn on =helm-autoresize-mode= and set both =helm-autoresize-max-height= and
=helm-autoresize-min-height= to the percentage of screen that you want Helm to occupy.

[fn:1] [[https://sam217pa.github.io/2016/09/13/from-helm-to-ivy/][From Helm to ivy]]
