#+SETUPFILE: ../setup.org
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./style.css"/>
#+HTML_HEAD_EXTRA: <link rel="icon" type="image/png" href="../favicon.png">
#+OPTIONS: toc:2 html-postamble:nil num:nil
#+BLOG_LINK_SOURCE: https://github.com/casouri/casouri.github.io
#+BLOG_LINK_LICENSE: https://creativecommons.org/licenses/by-sa/4.0/
#+TITLE: 想法
#+DATE: <2021-01-18 Mon>
#+MACRO: cemph <span class="cjk-emphasize">$1</span>

* 我心中的正射必中
<2021-04-20 Tue>

我对日本弓道理解不深，不知道“正射必中”在弓道里的背景知识，这里只说我的理解。

正射必中，从字面意义理解，就是姿势正确无误而射出的箭矢一定会中。从表面上看，这是废话：如果姿势正确射出的箭矢不中，难道姿势错误射出的箭能中？其实是可以的，即使姿势错误，运气好就也可以射中。但如果你射中只是因为运气好，而不是因为姿势正确，你会高兴吗？我觉得没什么可高兴的，我们的追求是用完美的体态技术射出一箭，而射中不过是我姿势技巧完美的结果罢了。追求射中而非技巧之完善无异于舍本逐末。射中不是目的，正射才是。这是我心中正射必中的含义。

这个道理在生活中随处可见，打游戏的时候，我一人力挽狂澜、碾压全场获得胜利让我快感最强烈，如果我操作拉跨，只是靠大腿队友赢，我心里反而有点别扭。因为让我感到快乐（爽）的是我技术的提高，表面上赢局没啥用。（不过我打低分局碾压也挺爽的，虽然理论上这只是表面上技术碾压。看来欺骗快感反馈挺简单？）与此相对，我就不太理解找别人带上分的逻辑：带上去以后你还是菜鸡，还要被高分段的人暴打掉回去，意义何在？还有锻炼身体时不关注实际的效果，只想着做够数量重量（听说有这种人）；背单词不管记不记得一律选“记得”，每天“背”几百个打卡；诸如此类。

要说我完全无法理解反方的动机，那我是在说谎。说到底就是装逼。反方的目的就是{{{cemph(看上去)}}}厉害。不同的目的，不同的逻辑。至于为什么看上去厉害而实质上弱鸡能让人快乐，为什么人能欺骗自己，可能的答案就太多了，我不打算深究。

有人会说，世界锦标赛也是靠射中射准评判高低，这显然是以射中为最终目的，射中作为最终目的也无不可。有趣的是，即使把射中作为最终目的，正射依然是最重要的：只有姿势正确才能真正百发百中。这就带来了两种正射必中：一种是为了稳定地射中而正射；另一种是单纯不追求射中而追求正射。其中之区别仅在审美：就我而言，射箭的魅力在于以完美的姿态技术射出一箭，因此我追求正射；对于世锦赛运动员而言，射箭的魅力在于超越极限的准确，因此追求射中。

总而言之，不管最终目的是正射还是射中，追求正射都能达到目的；反之，追求表面射中既不能正射，也没法真的稳定射中。同样有趣的是，这个道理也能用在之前举的生活例子上。可能有人认为追求虚荣并无不可且没人能避免，我不反对。人是社会动物，装逼的快乐谁也免不了。但是即使把装逼作为目的，追求表面的成功依旧虚假：被带上了高分后不能维持会被发现是个菜鸡；练半天身材没变好还是个菜鸡。也就是说，如若装逼，打铁要硬。有真东西而装逼没啥问题，有问题的是打肿脸充胖子。

我讲的是我心中的正射必中，别人心中当然也有自己的正射必中。比如“只要不断刻苦练习做到动作完美，就一定会射中”。这是从成长的角度思考，很高中弓道，但我觉得也可以。


* 这世界很大，大到人脑无法想象
<2021-01-30 Sat>

有没有看过老照片？黑白的照片上有十几个小孩子，对着镜头笑。我每次看到这样的照片都不禁想到，这些都是活生生的人，每个人在之后的几十年都有自己的人生，每个人有自己的人际关系，每个人都做了各种各样的事，每个人都产生了自己的想法和理念。仔细想一想，这是多么庞大的信息啊。想想我每天做的事，想的东西，和人的交流，看到的信息；在照片里的每个人都经历了这些。

不像游戏里NPC人物只有一点背景介绍和设定好的对话，现实生活中每个人都有完整复杂的人生。他们都在我不了解的地方互动生活。但由于这个世界太大，我对那部份世界一无所知。仅中国就有十四亿人，每天做自己的事情，思考自己的想法，有复杂的感情，复杂的人际关系，这个数量已经是人脑无法想象的天文数字。

我只能感叹世界之大之复杂。

* 你我凭什么花这么多钱？
<2021-01-18 Mon>

因为2020年的的流行传染病，很多美国的中国留学生提前回国。很多人走的时候留下不少东西，最近我帮同学给他们的朋友收拾东西：一些东西寄回国，另一些我们拿去用，剩下的扔掉。我的同学都很爽，开了两个箱子，白嫖了两万美元的衣服。当然，拿去卖是卖不了两万美元的，但是买的时候两万是实打实的。

想一想六亿人月收入不足一千，贫困山区有人吃不上饭，大厂996加班，拼多多加班到猝死，这是不是“路有冻死骨，朱门酒肉臭”？这有钱同学家里大概是做生意的，他挥霍的钱大概也是从劳动者那里吸来的血吧？劳动者拼死拼活冒着工伤和疲惫创造的价值，被这个人在美国换成一堆一文不值的衣服然后又扔掉。凭什么有人有的人在山里吃咸菜，一年买不了一件新衣服，有人在格子间里燃烧生命，有人在美国买衣服买鞋，喝酒撕逼，找人代写作业混文凭？

但是仔细一想，我和这些我看不起的人好像也没有本质上的区别。虽然我出身工薪家庭，好像没有什么剩余价值可剥削，但是作为北京城市居民，我也没少享受城市居民身份带给我的隐性福利。比如农民工，卫生保洁人员，餐厅服务生，快递员奋力工作却领取微薄的薪水，养肥资本家的同时还要给我提供廉价的服务。他们做这些“不体面的工作”，让我能“体面地”生活工作。

诚然，我并不是自愿剥削这些人，直接剥削他们的也不是我，但那个同学也不是自愿剥削别人。如果要我减去一切花销，不买游戏，不买CD，不买好吃的，把钱都捐给山区，我做不到。这样我似乎也没理由看不过两万哥随便花钱买衣服、鞋、车。或许可以说他买的是奢侈品，属于挥霍无度的生活，我买的不是奢侈品，是“普通生活水平”，所以他值得谴责而我不应该被谴责。但是“普通生活水平”怎么定义呢？按不同的标准，我的生活可能是普通生活水平，也可能是挥霍无度。

所以我该怎么想？我不知道。


