#+SETUPFILE: ../../setup.org
#+TITLE: How Long Should a Paragraph Be on the Web?
#+DATE: <2021-02-01 Mon>
#+TAGS: Web Aesthetic

I often find that a screen full of text on the web is much more confusing and tiring to read than a page full of text in a physical book, even though the latter usually contains much more text. My theory is that when reading a physical book, you have (or at least feel) more control of your location and surroundings: you are presented with two pages side-by-side and can easily flip to previous and next page.

On the other hand, when you read an article in a browser, you see the article only through this small window, that’s far less scope than a physical book. And if you think of the prose as a map, you are given a much smaller map and naturally feels less clear of your location and surroundings.

Worse, instead of flipping pages and seeing the pages with no lag, you have to scroll to see the other parts. Scrolling is less precise, slower and harder keep track of mentally: at least for me, it is not easy to keep track of how far did I scroll, what I scrolled over, etc.

In a word, comparing to reading on a physical book, you mental map of the prose is greatly obfuscated when you scroll over it in a browser.

To mitigate this, I try to place landmarks around the prose to help the read keep track of their position and surrounding, or at least giving them the feeling of in control. I try to make sure at any given moment, the reader can see at least one or two headers, images, or anything other than a blob of text in the screen. That, in my experience, makes reading in a browser more comfortable.
