#+SETUPFILE: ../setup.org
#+TITLE: {{{day_title}}}
#+DATE: <2018-11-22 Thu>

{{{day_link}}}

{{{img(the-beatles--sgt-peppers-lonely-heats-band.png)}}}

*The Beatles - [[https://www.youtube.com/watch?v=VtXl8xAPAtA&list=PL3PhWT10BW3VDM5IcVodrdUpVIhU8f7Z][Sgt. Pepper's Lonely Hearts Club Band]] - [[https://en.wikipedia.org/wiki/Sgt._Pepper%2527s_Lonely_Hearts_Club_Band][Sgt. Pepper's Lonely Hearts Club Band]] - 1967*

*The Beatles - [[https://www.youtube.com/watch?v=0C58ttB2-Qg&index=2&list=PL3PhWT10BW3VDM5IcVodrdUpVIhU8f7Z-][With A Little Help From My Friends]] - [[https://en.wikipedia.org/wiki/Sgt._Pepper%2527s_Lonely_Hearts_Club_Band][Sgt. Pepper's Lonely Hearts Club Band]] - 1967*

（这两首歌在同一油管列表里）

*Sgt. Pepper's Lonely Hearts Club Band*

{{{BEGIN_LYRICS}}}
[Verse 1] \\
It was twenty years ago today \\
Sgt. Pepper taught the band to play \\
They've been going in and out of style \\
But they're guaranteed to raise a smile \\
So may I introduce to you \\
The act you've known for all these years \\
Sgt. Pepper's Lonely Hearts Club Band \\
 \\
[Bridge] \\
We're Sgt. Pepper's Lonely Hearts Club Band \\
We hope you will enjoy the show \\
Sgt. Pepper's Lonely Hearts Club Band \\
Sit back and let the evening go \\
Sgt. Pepper's Lonely, Sgt. Pepper's Lonely \\
Sgt. Pepper's Lonely Hearts Club Band \\
It's wonderful to be here \\
It's certainly a thrill \\
You're such a lovely audience \\
We'd like to take you home with us \\
We'd love to take you home \\
 \\
[Verse 2] \\
I don't really want to stop the show \\
But I thought you might like to know \\
That the singer's going to sing a song \\
And he wants you all to sing along \\
So let me introduce to you \\
The one and only Billy Shears \\
And Sgt. Pepper's Lonely Hearts Club Band \\
{{{END_LYRICS}}}

*With A Little Help From My Friends*

{{{BEGIN_LYRICS}}}
[Segue: The Beatles] \\
Billy Shears! \\
 \\
[Verse 1: Ringo Starr] \\
What would you think if I sang out of tune? \\
Would you stand up and walk out on me? \\
Lend me your ears and I'll sing you a song \\
And I'll try not to sing out of key \\
 \\
[Chorus: Ringo Starr] \\
Oh, I get by with a little help from my friends \\
Mm, I get high with a little help from my friends \\
Mm, gonna try with a little help from my friends \\
 \\
[Verse 2: Ringo Starr & The Beatles] \\
What do I do when my love is away? \\
Does it worry you to be alone? \\
How do I feel by the end of the day? \\
Are you sad because you're on your own? \\
 \\
[Chorus: Ringo Starr] \\
No, I get by with a little help from my friends \\
Mm, get high with a little help from my friends \\
Mm, gonna try with a little help from my friends \\
 \\
[Bridge: Ringo Starr & The Beatles] \\
Do you need anybody? \\
I need somebody to love \\
Could it be anybody? \\
I want somebody to love \\
 \\
 \\
[Verse 3: Ringo Starr & The Beatles] \\
Would you believe in a love at first sight? \\
Yes, I'm certain that it happens all the time \\
What do you see when you turn out the light? \\
I can't tell you, but I know it's mine \\
 \\
[Chorus: Ringo Starr] \\
Oh, I get by with a little help from my friends \\
Mm, get high with a little help from my friends \\
Oh, I'm gonna try with a little help from my friends \\
 \\
[Bridge: Ringo Starr & The Beatles] \\
Do you need anybody? \\
I just need someone to love \\
Could it be anybody? \\
I want somebody to love \\
 \\
[Outro: Ringo Starr] \\
Oh, I get by with a little help from my friends \\
Mm, gonna try with a little help from my friends \\
Oh, I get high with a little help from my friends \\
Yes, I get by with a little help from my friends \\
With a little help from my friends \\
{{{END_LYRICS}}}
