#+SETUPFILE: ../setup.org
#+TITLE: {{{day_title}}}
#+DATE: <2020-09-13 Sun 12:57>

{{{day_link}}}

{{{img(janis-joplin--i-got-dem-ol-kozmic-blues-again-mama.png)}}}

*Janis Joplin - [[https://youtu.be/zad3bDnjsII][Maybe]] - I Got Dem Ol' Kozmic Blues Again Mama! - 1969*

最近没听什么新东西，发个不新的吧www

{{{BEGIN_LYRICS}}}
Maybe \\
Oh if I could pray and I try, dear, \\
You might come back home, home to me. \\
 \\
Maybe \\
Whoa, if I could ever hold your little hand \\
Oh you might understand. \\
Maybe, maybe, maybe, maybe, yeah. \\
 \\
Maybe, maybe, maybe, maybe, maybe dear \\
I guess I might have done something wrong, \\
Honey I'd be glad to admit it. \\
Oh, come on home to me! \\
Honey maybe, maybe, maybe, maybe yeah. \\
 \\
Well I know that it just doesn't ever seem to matter, baby, \\
Oh honey, when I go out or what I'm trying to do, \\
Can't you see I'm still left here \\
And I'm holding on in needing you. \\
 \\
Please, please, please, please, \\
Oh won't you reconsider babe. \\
Now come on, I said come back, \\
Won't you come back to me! \\
 \\
Maybe dear, oh maybe, maybe, maybe, \\
Let me help you show me how. \\
Honey, maybe, maybe, maybe, maybe, \\
Maybe, maybe, maybe, yeah, \\
Maybe, maybe, maybe, yeah. \\
Ooh! \\
{{{END_LYRICS}}}
