#+SETUPFILE: ../setup.org
#+TITLE: {{{day_title}}}
#+DATE: <2020-12-15 Tue 18:31>
#+OPTIONS: num:nil

{{{day_link}}}

{{{img(beatles--abbey-road.jpg)}}}

*Beatles - The End - Abbey Road - 1969*

万物皆有终结。 /Abbey Road/ 是最后一张 Beatles 专辑。最后一首歌 /The End/ 结束后，再也不会有更多的 Beatles 歌曲在世上出现。同样，大二数学课上看到学姐到现在大四过半，不到两年的单恋也结束了[fn:1]。The fab four 从四个夹克皮裤的反叛分子在 Hamburg 夜店摇滚，到四个西装拖把头男孩横扫世界，到四个迷幻嬉皮士青年为流行乐带来创新，到天台演唱会上四个严肃的摇滚男人最后一次现场演出。他们经历了传奇的八年，整个世界被四个人改变，他们自己也有翻天覆地的变化。

我经过这两年成长了些吗？两年时间毕竟不长，我的变化没有太大。我懂得更多知识，会做更多的菜，身体变好了些，认识了更多单词，余日摇滚写了五十多篇，玩 Splatoon 变强了一些，头发长到披肩……好像唯独感情上没感觉更成熟。不过没关系，以后会变好的。

和学姐聊过之后，心情轻松了很多，虽然心中依然空荡，但是之后也会变好吧。Beatles 解散的时候心中会不会也有这样的感情呢？虽然没有什么亲密的关系了（本来也基本没有），但学姐依然还在我的生活中，想聊天时还是有人理我。所以还不算太坏？

​/Golden Slumbers/ 里 Paul 的嘶吼，​/Carry That Weight/​ 里四个人的合唱，​/The End/ 里 Ringo 的鼓独奏，Paul，George 和 John 的吉他独奏，都让我汗毛倒竖，心中充满感动。最后的 /The End/ 结束后，心中有种奇妙的感受。

现在，请允许我介绍， /Abbey Road/ 之，[[https://youtu.be/a4Ujexj9YGs][B面]]！

* You Never Give Me Your Money
{{{BEGIN_LYRICS}}}
You never give me your money \\
You only give me your funny paper \\
And in the middle of negotiations \\
You break down \\
 \\
I never give you my number \\
I only give you my situation \\
And in the middle of investigation \\
I break down \\
 \\
Out of college, money spent \\
See no future, pay no rent \\
All the money's gone, nowhere to go \\
Any jobber got the sack \\
Monday morning, turning back \\
Yellow lorry slow, nowhere to go \\
But oh, that magic feeling, nowhere to go \\
Oh, that magic feeling, nowhere to go \\
Nowhere to go \\
 \\
Aaaaahhhhhhhhhh... \\
Aaaaahhhhhhhhhh... \\
Aaaaahhhhhhhhhh... \\
 \\
One sweet dream \\
Pick up the bags and get in the limousine \\
Soon we'll be away from here \\
Step on the gas and wipe that tear away \\
One sweet dream came true today \\
Came true today \\
Came true today (Yes it did) \\
 \\
One two three four five six seven \\
All good children go to Heaven \\
... \\
{{{END_LYRICS}}}

* Sun King
{{{BEGIN_LYRICS}}}
Aaaaahhhhhhhhhh... \\
Here comes the Sun King \\
Here comes the Sun King \\
Everybody's laughing \\
Everybody's happy \\
Here comes the Sun King \\
 \\
Quando paramucho mi amore de felice carathon \\
Mundo paparazzi mi amore cicce verdi parasol \\
Questo abrigado tantamucho que canite carousel \\
{{{END_LYRICS}}}

* Mean Mr. Mustard
{{{BEGIN_LYRICS}}}
Mean Mister Mustard sleeps in the park \\
Shaves in the dark trying to save paper \\
Sleeps in a hole in the road \\
Saving up to buy some clothes \\
Keeps a ten-bob note up his nose \\
Such a mean old man \\
Such a mean old man \\
 \\
His sister Pam works in a shop \\
She never stops, she's a go-getter \\
Takes him out to look at the queen \\
Only place that he's ever been \\
Always shouts out something obscene \\
Such a dirty old man \\
Dirty old man \\
{{{END_LYRICS}}}

* Polythene Pam
{{{BEGIN_LYRICS}}}
Well you should see Polythene Pam \\
She's so good-looking but she looks like a man \\
Well you should see her in drag dressed in her polythene bag \\
Yes you should see Polythene Pam \\
Yeah yeah yeah \\
 \\
Get a dose of her in jackboots and kilt \\
She's killer-diller when she's dressed to the hilt \\
She's the kind of a girl that makes the "News of the World" \\
Yes you could say she was attractively built \\
Yeah yeah yeah \\
{{{END_LYRICS}}}

* She Came In Through The Bathroom Window
{{{BEGIN_LYRICS}}}
(Gonna come out now \\
Ha ha ha \\
Wow look out.) \\
 \\
She came in through the bathroom window \\
Protected by a silver spoon \\
But now she sucks her thumb and wonders \\
By the banks of her own lagoon \\
 \\
Didn't anybody tell her? \\
Didn't anybody see? \\
Sunday's on the phone to Monday \\
Tuesday's on the phone to me \\
 \\
She said she'd always been a dancer \\
She worked at fifteen clubs a day \\
And though she thought I knew the answer \\
Well, I knew what I could not say \\
 \\
And so I quit the police department \\
And got myself a steady job \\
And though she tried her best to help me \\
She could steal, but she could not rob \\
 \\
Didn't anybody tell her? \\
Didn't anybody see? \\
Sunday's on the phone to Monday \\
Tuesday's on the phone to me, oh yeah \\
{{{END_LYRICS}}}

* Golden Slumbers
{{{BEGIN_LYRICS}}}
Once, there was a way to get back homeward \\
Once, there was a way to get back home \\
Sleep, pretty darling, do not cry \\
And I will sing a lullaby \\
 \\
Golden slumbers fill your eyes \\
Smiles awake you when you rise \\
Sleep, pretty darling, do not cry \\
And I will sing a lullaby \\
 \\
Once, there was a way to get back homeward \\
Once, there was a way to get back home \\
Sleep, pretty darling, do not cry \\
And I will sing a lullaby \\
{{{END_LYRICS}}}

* Carry That Weight
{{{BEGIN_LYRICS}}}
Boy, you're gonna carry that weight, \\
Carry that weight a long time \\
Boy, you're gonna carry that weight \\
Carry that weight a long time \\
 \\
I never give you my pillow \\
I only send you my invitations \\
And in the middle of the celebrations \\
I break down \\
 \\
Boy, you're gonna carry that weight \\
Carry that weight a long time \\
Boy, you're gonna carry that weight \\
Carry that weight a long time \\
{{{END_LYRICS}}}

* The End
{{{BEGIN_LYRICS}}}
Oh yeah, all right \\
Are you going to be in my dreams \\
Tonight? \\
 \\
[Drum solo] \\
 \\
[Guitar solos] \\
 \\
And in the end \\
The love you take \\
Is equal to the love \\
You make \\
{{{END_LYRICS}}}

P.S. Beatles 课也结束了，毕竟期末了呢。

[fn:1] 我知道你在想啥，“搞半天是单恋啊，噗哧，小处男”。不，具体情况很复杂，但和互联网无关路人就没关系了（
