#+SETUPFILE: ../setup.org
#+TITLE: {{{day_title}}}
#+DATE: <2020-12-14 Mon 08:58>

{{{day_link}}}

{{{img(janis-joplin--pearl.png)}}}

*Janis Joplin - [[https://www.youtube.com/results?search_query=janis+joplin+a+woman+left+lonely][A Woman Left Lonely]] - Pearl - 1971*

又失恋了，环视一圈居然没有人能倾诉，或者说，我想倾诉吗？这次居然没有两年前一样的痛苦，大概这两年间被幸福这把warm gun枪杀了一次又一次，我的神经已经麻木了。虽然不是完全符合，但是这是我现在想到最近的一首歌。一首​/A Woman Left Lonely/​送给大家。

{{{BEGIN_LYRICS}}}
A woman left lonely will soon grow tired of waiting, \\
She'll do crazy things, yeah, on lonely occasions. \\
A simple conversation for the new men now and again \\
Makes a touchy situation when a good face come into your head. \\
And when she gets lonely, she's thinking 'bout her man, \\
She knows he's taking her for granted, yeah yeah, \\
Honey, she doesn't understand, no no no no!  \\
 \\
Well, the fevers of the night, they burn an unloved woman \\
Yeah, those red-hot flames try to push old love aside. \\
A woman left lonely, she's the victim of her man, yes she is. \\
When he can't keep up his own way, good Lord, \\
She's got to do the best that she can, yeah! \\
A woman left lonely, Lord, that lonely girl, \\
Lord, Lord, Lord! \\
{{{END_LYRICS}}}

P.S. 给大家一个经验，如果一个人一开始不喜欢你，天天聊天聊两年也不会变得喜欢你，所以不要挣扎了，接受现实。当然，大概没人真的能失望至极之前放弃。

P.P.S 上周刚买到口琴的时候学了个调很高兴地准备分享给她炫耀，最后因为各种原因没有没机会发。现在放到这里吧。

#+begin_export html
<audio controls src="../misc/love-me-do.m4a">Love Me Do</audio>
#+end_export
