#+SETUPFILE: ./setup.org
#+HTML_LINK_UP: ./index.html
#+TITLE: 金鱼的外置记忆体

由于我们金鱼的记忆过于拉胯，一些重要信息有必要记录在外置记忆体里。

#+begin_quote
　　所以我时常害怕，愿中国青年都摆脱冷气，只是向上走，不必听自暴自弃者流的话。能
做事的做事，能发声的发声。有一分热，发一分光，就令萤火一般，也可以在黑暗里发一点
光，不必等候炬火。

　　此后如竟没有炬火：我便是唯一的光。倘若有了炬火，出了太阳，我们自然心悦诚服的
消失，不但毫无不平，而且还要随喜赞美这炬火或太阳；因为他照了人类，连我都在
内。

　　我又愿中国青年都只是向上走，不必理会这冷笑和暗箭。

随感录四十一 \\
一九一九年 \\
鲁迅
#+end_quote

#+begin_quote
不管资本再怎么用漂亮的东西装饰自己，也掩盖不了它惟一的目地只是压榨和剥削[fn:1]。因此，看到它再怎么短视，贪婪和邪恶都不用惊讶。听其言而观其行，中国的资本在行动上又特别地率直，不用学资本论也能看出来它想干啥。

二〇二〇年五月 \\
我
#+end_quote

** 二〇二〇年四月，员工拒绝加班被判赔公司1.8万
法官：员工有权拒绝加班，但遇紧急任务要求加班必须服从。
** 二〇二〇年四月，腾讯，[[./阅文集团的奴隶合同.org][阅文集团的奴隶合同]]
基本上：版权归腾讯，他们拿你的书想干嘛干嘛，改成免费模式也不用跟你商量。作者不算雇员啥劳动法福利都没有。
** 二〇一九年十一月，华为，[[./251事件.org][251事件]]
引用[[https://zh.wikipedia.org/wiki/華為251事件][维基百科]]：原华为技术有限公司的员工李洪元在离职后，被华为以职务侵占（先被改为泄露商业机密，后再被改为敲诈勒索）为由向警方举报而被羁押251日，因证据不足而获检察院不起诉处分并释放。
** 二〇一九年五月，百度，删了百度贴吧2017年以前所有的帖子
** 二〇一九年四月，马云：996是修来的福报，很多人想做没机会
** 二〇一久年三月，[[https://996.icu/#/zh_CN][996.icu]]
“996”工作制，即每天早 9 点到岗，一直工作到晚上 9 点，每周工作 6 天。
** 二〇一九年，腾讯，爱奇艺，超前点播
超前点播：会员再次付费50元即可获得超前点播特权，将始终比会员多看6集。会员合同：腾讯/爱奇艺保留对会员权益随意更改的权利。
** 二〇一六年，百度，魏则西事件，莆田系医院
百度搞搜索结果竞价排名，魏泽西搜百度去了推荐的莆田系医院，被骗大量钱财，不治身亡。
** 二〇一六年一月，百度，血友病吧事件
血友病吧等一些疾病类贴吧吧主管理员等等被百度售卖。[[https://zh.wikipedia.org/wiki/对百度的争议][百度做的恶]]
** 二零一五年，淘宝微信互相封杀
** 二〇一〇年，奇虎360，腾讯QQ，三Q大战
2010年9月，奇虎针对腾讯QQ先后发布了360隐私保护器和360扣扣保镖，并称其可以保护QQ用户的隐私和网络安全。11月3日，腾讯宣布在装有360软件的电脑上将不能运行QQ软件[3]。

[fn:1] 严格来说是通过压榨和剥削自我增殖
